# build environment
FROM node:14-slim as builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package-lock.json package-lock.json
COPY package.json package.json
RUN npm install
COPY . ./
COPY .env.production .env
RUN npm run build

# production environment
FROM nginx:1.20
COPY --from=builder /app/build /usr/share/nginx/html

# Copy the default nginx.conf 
COPY ./deploy/nginx.conf /etc/nginx/conf.d/default.conf

# EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]