export var STATUS_RESPONSE;
(function (STATUS_RESPONSE) {
    STATUS_RESPONSE["SUCCESS"] = "success";
    STATUS_RESPONSE["ERROR"] = "error";
})(STATUS_RESPONSE || (STATUS_RESPONSE = {}));
export var STATUS_RESPONSE_CODE;
(function (STATUS_RESPONSE_CODE) {
    STATUS_RESPONSE_CODE[STATUS_RESPONSE_CODE["ERROR"] = 400] = "ERROR";
    STATUS_RESPONSE_CODE[STATUS_RESPONSE_CODE["SUCCESS"] = 200] = "SUCCESS";
})(STATUS_RESPONSE_CODE || (STATUS_RESPONSE_CODE = {}));
export var ORDER_DIRECTION;
(function (ORDER_DIRECTION) {
    ORDER_DIRECTION["ASC"] = "ASC";
    ORDER_DIRECTION["DESC"] = "DESC";
    ORDER_DIRECTION["NO"] = "";
})(ORDER_DIRECTION || (ORDER_DIRECTION = {}));
export var TYPE_BLOCK_CHAIN;
(function (TYPE_BLOCK_CHAIN) {
    TYPE_BLOCK_CHAIN["INCREASE_ALLOWANCE"] = "increaseAllowance";
    TYPE_BLOCK_CHAIN["INCREASE_BALANCE"] = "Insufficient balance";
})(TYPE_BLOCK_CHAIN || (TYPE_BLOCK_CHAIN = {}));
export var STATUS_RESPONSE_SMART_CONTRACT;
(function (STATUS_RESPONSE_SMART_CONTRACT) {
    STATUS_RESPONSE_SMART_CONTRACT["ENABLE_METAMASK_SUCCESS"] = "ENABLE_METAMASK_SUCCESS";
    STATUS_RESPONSE_SMART_CONTRACT["ENABLE_METAMASK_ERROR"] = "ENABLE_METAMASK_ERROR";
    STATUS_RESPONSE_SMART_CONTRACT["UNLOCK_METAMASK"] = "UNLOCK_METAMASK";
    STATUS_RESPONSE_SMART_CONTRACT["CONNECT_BNB_SMART_CHAIN_TESTNET_SUCCESS"] = "CONNECT_BNB_SMART_CHAIN_TESTNET_SUCCESS";
    STATUS_RESPONSE_SMART_CONTRACT["CONNECT_BNB_SMART_CHAIN_TESTNET_ERROR"] = "CONNECT_BNB_SMART_CHAIN_TESTNET_ERROR";
    STATUS_RESPONSE_SMART_CONTRACT["DETECT_CHAIN_ID"] = "DETECT_CHAIN_ID";
})(STATUS_RESPONSE_SMART_CONTRACT || (STATUS_RESPONSE_SMART_CONTRACT = {}));
