export var STATUS_EVENT;
(function (STATUS_EVENT) {
    STATUS_EVENT["SCHEDULED"] = "Scheduled";
    STATUS_EVENT["ACTIVATING"] = "Activating";
    STATUS_EVENT["ENDED"] = "Ended";
})(STATUS_EVENT || (STATUS_EVENT = {}));
export var STATUS_REFERRAL_CODE;
(function (STATUS_REFERRAL_CODE) {
    STATUS_REFERRAL_CODE["CLAIMING"] = "Claiming";
    STATUS_REFERRAL_CODE["CLAIMED"] = "Claimed";
    STATUS_REFERRAL_CODE["NOT_CLAIM_YET"] = "Not Claim Yet";
})(STATUS_REFERRAL_CODE || (STATUS_REFERRAL_CODE = {}));
