export const emptyReportDetail = {
    date: "",
    updatedAt: "",
    id: 0,
    blockNumber: "",
    timeStamp: "",
    hash: "",
    nonce: "",
    blockHash: "",
    transactionHash: "",
    from: "",
    contractAddress: "",
    to: "",
    price: "",
    tokenName: "",
    tokenSymbol: "",
    tokenDecimal: "",
    transactionIndex: "",
    gas: "",
    type: "",
    gasPrice: "",
    gasUsed: "",
    cumulativeGasUsed: "",
    confirmations: "",
    listingFee: 0,
    donationFee: 0,
    filter: "",
};
